lastLng = VAR _MaxTime =
    CALCULATE (
        MAX ( data[Document.time] ),
        KEEPFILTERS ( ALL ( data[Document.time] ) )
    )
RETURN
    CALCULATE ( SUM ( data[Document.longitude] ), data[Document.time] = _MaxTime )